### ISSUE TITLE
ExpandedTileController is disposed too soon

### ISSUE THREAD

**Issue by eggzotic** [micwaziz/flutter_expanded_tile#1]
Hi - love the idea of an ExpandedTile that we can control externally via the controller. However I find that after the ExpandedTile scrolls off the screen that the ExpandedTileController is disposed - so it breaks when I have a reference to it (e.g. from the onPressed of a button in the BottomAppBar) when it scrolls back onto the screen! Can we keep the controller alive so it can persist the whole life of the buttons that wish to control it?

**Comment by micazi** [comment]
Thanks, Noted!
Will take care of it in the next version.

**Comment by alejandrogiubel** [comment]
I have the same problem. It is a very useful widget but I lost the controller when make some visual update with the ExpansionTile (e.g. Delete an ExpansionTile, Add an ExpansionTile) for some reazon the ExpansionTileControllers is disposed.

**Comment by alejandrogiubel** [comment]
Any update?

**Comment by micazi** [comment]
Closed and updated in version 0.3.0
Sorry, I haven't been active lately.
Thank you for your support!
