### ISSUE TITLE
flutter_expanded_tile.dart:359:21: Error: Required named parameter 'vsync' must be provided.

### ISSUE THREAD

**Issue by fabioselau077** [micwaziz/flutter_expanded_tile#10]
../../.pub-cache/hosted/pub.dartlang.org/flutter_expanded_tile-0.3.6/lib/flutter_expanded_tile.dart:359:21: Error: Required named parameter 'vsync' must be provided.
        AnimatedSize(
                    ^
../../fvm/versions/stable/packages/flutter/lib/src/widgets/animated_size.dart:56:9: Context: Found this candidate, but the arguments don't match.

  const AnimatedSize({
        ^^^^^^^^^^^^

**Comment by micazi** [comment]
I can't recreate this error.
Could you share a snippet I can work on? or perhaps could you try clearing your pub cache and telling me how it went? 
Thanks!
Thank you for your contribution & Sorry for the late replies.

**Comment by WoodyLi03** [comment]
How did you solve this problem? I also ran into this problem

**Comment by micazi** [comment]
Closing for now, if it reappeared just open a new issue. Thank you!
