### ISSUE TITLE
Calling toggle() requires two clicks for initial open

### ISSUE THREAD

**Issue by johnmastri** [micwaziz/flutter_expanded_tile#11]
I create several widgets using a loop and a switch statement - when you first click on a tile, it does nothing. The second click then initiates the expansion. From there, the expansion/collapse works as expected. Any suggestions to get this working correctly on first click? (using Flutter for web btw)

```  
for (var a = 0; a < menuOptions.length; a++) {

      Widget w;
      //late ExpandedTileController expandedTileController;

      switch (menuOptions[a].type) {
        case "section":

          ExpandedTileController expandedTileController = ExpandedTileController();

        w = ExpandedTile(
          theme: const ExpandedTileThemeData(

          ),
          title: Text(menuOptions[a].name),
          controller: expandedTileController,
          content: Container(width: 100, height: 100, color: Colors.blue),
          onTap: () {
            print(expandedTileController.isExpanded);
            expandedTileController.toggle();
          }
        );
```

**Comment by micazi** [comment]
I am absolutely sorry for the late reply, There have been a few updates regarding the issue, and I added a listview builder for this use-case. could you give it a try and report back? Thank you for your contribution!
