### ISSUE TITLE
Initial(default) Expanded item in ExpandedTileList.builder

### ISSUE THREAD

**Issue by DharmeshO7** [micwaziz/flutter_expanded_tile#16]
The initial expanded item is not showing when using it with ExpandedTileList.builder

`controller: index == 1
    ? controller.copyWith(isExpanded: true)
    : controller,`

**Comment by gengiscb** [comment]
Also I can confirm that  controller.copyWith(isExpanded: true) is not working, any fix?

**Comment by tanzeemhussain** [comment]
yeah I also faced this issue

**Comment by micazi** [comment]
Closed and updated in version 0.4.0
Sorry, I haven't been active lately.
Thank you for your support!
