### ISSUE TITLE
How to eliminate the triling icon?

### ISSUE THREAD

**Issue by alejandrogiubel** [micwaziz/flutter_expanded_tile#2]
How to eliminate the triling icon?
![Sin título](https://user-images.githubusercontent.com/36578847/104079452-71b5b980-5223-11eb-836a-26a24ac8a312.png)

**Comment by micazi** [comment]
There's no option to remove the icon right now, but you can assign an icon
with color: Colors.transparent

**Comment by alejandrogiubel** [comment]
Ok thanks.
