### ISSUE TITLE
Hi, its giving me undefined class error 

### ISSUE THREAD

**Issue by innerk** [micwaziz/flutter_expanded_tile#5]
after flutter pub get, and importing the library

Undefined class 'ExpandedTileController'.
Try changing the name to the name of an existing class, or creating a class with the name 'ExpandedTileController'.dart(undefined_class)

**Comment by green-horne** [comment]
did you already try to import 'tileController.dart' in your file?

**Comment by micazi** [comment]
you now only need to import the master file "flutter_expanded_tile.dart"!
Closed and updated in version 0.3.0
Sorry, I haven't been active lately.
Thank you for your support!
