### ISSUE TITLE
itembuilder

### ISSUE THREAD

**Issue by green-horne** [micwaziz/flutter_expanded_tile#6]
Hello, I'm very happy about your plugin! But I need to use a datalist to fill contents ... is there a way to use itembuilder or could you tell me, how i can place the values of the list into the textfields?

**Comment by micazi** [comment]
Yes, just use a 'listview.builder' and give the ExpandedTile widget a new controller, and that's it!
Closed and updated in version 0.3.0
Sorry, I haven't been active lately.
Thank you for your support!
