### ISSUE TITLE
ExpandedTile.builder and seperated not showing

### ISSUE THREAD

**Issue by asadbekdev** [micwaziz/flutter_expanded_tile#8]
there is nothing in ui
they're not working !

**Comment by micazi** [comment]
Would love to see some more information to be able to troubleshoot the problem..

**Comment by asadbekdev** [comment]
![image](https://user-images.githubusercontent.com/67022917/142751652-87769530-9088-4cb1-b52d-81e54fe5038b.png)

**Comment by asadbekdev** [comment]
![image](https://user-images.githubusercontent.com/67022917/142751660-a254d0d6-a0e1-42e6-9391-94c03927285f.png)

**Comment by asadbekdev** [comment]
![image](https://user-images.githubusercontent.com/67022917/142751673-a5cccc47-e960-4202-83d2-465348f3ebaa.png)
Data is coming but in ui show nothing

**Comment by asadbekdev** [comment]
ExpandedTile working but ExpandedTile.builder() not working

**Comment by micazi** [comment]
Thank you for the screenshots, but I need a reproducible code.
And if there are any exceptions thrown that should be the most helpful.
Thank you.

**Comment by asadbekdev** [comment]
class CustomDrawer extends StatelessWidget {
  CustomDrawer({
    Key? key,
  }) : super(key: key);
  // final List<Category> _categories = getCategories();

  @override
  Widget build(BuildContext context) {
    return Drawer(
      child: ListView(
        children: [
          // DRAWER TITLE
          Padding(
            padding: EdgeInsets.symmetric(
              horizontal: getProportionateScreenWidth(kDefaultPadding),
              vertical: getProportionateScreenHeight(kDefaultPadding + 5),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  "Bo'limlar",
                  style: TextStyle(
                    fontSize: getProportionateScreenWidth(24.0),
                    color: kSecondaryTextColor,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                // CLOSE DRAWER BUTTON
                GestureDetector(
                  onTap: () => Navigator.pop(context),
                  child: SvgPicture.asset('assets/icons/x_icon.svg'),
                )
              ],
            ),
          ),
          // DRAWER DIVIDER
          Row(
            children: [
              Expanded(
                child: Divider(
                  color: kSecondaryTextColor.withOpacity(0.15),
                  thickness: 1.0,
                ),
              ),
            ],
          ),
          // BODY
          FutureBuilder(
            future: CategoriesService().getAllCategoires(),
            builder: (context, AsyncSnapshot snapshot) {
              if (snapshot.hasData) {
                print(snapshot.data);
                ExpandedTileList.builder(
                  maxOpened: 1,
                  shrinkWrap: true,
                  reverse: true,
                  itemCount: 2,
                  itemBuilder: (context, index, controller) {
                    Category _cat = snapshot.data[index];
                    print("hello");
                    return _categoryItem(
                      index: index,
                      controller: controller,
                      categoryTitle: _cat.title,
                      childs: _cat.childs,
                    );
                  },
                );
              } else if (snapshot.hasError) {
                print(snapshot.error);
                return Container();
              }
              return Container();
            },
          ),
        ],
      ),
    );
  }

  ExpandedTile _categoryItem(
      {required index,
      required controller,
      required categoryTitle,
      required childs}) {
    return ExpandedTile(
      theme: ExpandedTileThemeData(
        headerColor: const Color(0xFFf4f4f4),
        headerSplashColor: kSecondaryTextColor.withOpacity(0.10),
        headerRadius: 8.0,
        headerPadding: EdgeInsets.all(
          getProportionateScreenWidth(12.0),
        ),
        contentPadding: EdgeInsets.zero,
        titlePadding: EdgeInsets.only(left: getProportionateScreenWidth(8.0)),
        contentBackgroundColor: Colors.transparent,
      ),
      controller:
          index == 1 ? controller.copyWith(isExpanded: true) : controller,
      expansionAnimationCurve: Curves.ease,
      expansionDuration: const Duration(milliseconds: 900),
      leading: SvgPicture.asset('assets/icons/book_icon.svg'),
      title: Text(
        categoryTitle!,
        style: TextStyle(
          fontSize: getProportionateScreenHeight(18.0),
          fontWeight: FontWeight.w500,
          color: kSecondaryTextColor,
        ),
      ),
      trailing: SvgPicture.asset('assets/icons/arrow_down.svg'),
      trailingRotation: 180.0,
      contentSeperator: 0.0,
      content: Container(
        margin: EdgeInsets.only(left: getProportionateScreenWidth(16.0)),
        decoration: const BoxDecoration(
          border: Border(
            left: BorderSide(color: Color(0xFFf4f4f4), width: 2.5),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            ...List.generate(
              childs!.length,
              (index) => Padding(
                padding: EdgeInsets.symmetric(
                  vertical: getProportionateScreenHeight(16.0),
                  horizontal: getProportionateScreenWidth(kDefaultPadding),
                ),
                child: TextButton(
                  onPressed: () {},
                  child: Text(
                    childs![index]["title"],
                    style: TextStyle(
                      fontWeight: FontWeight.w400,
                      fontSize: getProportionateScreenWidth(16.0),
                      color: kSecondaryTextColor.withOpacity(0.8),
                    ),
                  ),
                  style: TextButton.styleFrom(
                    backgroundColor: Colors.transparent,
                    padding: EdgeInsets.zero,
                    tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                    minimumSize: const Size(0, 0),
                    splashFactory: NoSplash.splashFactory,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
      onTap: () {
        debugPrint("tapped!!");
      },
      onLongTap: () {
        debugPrint("long tapped!!");
      },
    );
  }

**Comment by micazi** [comment]
you should add 'return' before the Listview.builder because this is obviously a return statement.
has nothing to do with the package.
Thank you, Closed.
