### ISSUE TITLE
how to disable expand content when child is empty

### ISSUE THREAD

**Issue by dickyjayaumbara** [micwaziz/flutter_expanded_tile#9]
can we don't expand the content when content is empty because I have a condition, not all lists have children, please help.

**Comment by micazi** [comment]
Not emplemented yet, but that's an interesting addidtion. I will add an 'enabled' parameter in the next release.
Thank you!

**Comment by dickyjayaumbara** [comment]
Great, sure you are welcome, can't wait for it to be released soon, hopefully, it can be used as soon as possible hehe :)

**Comment by micazi** [comment]
Updated in V0.3.6 
Thank you for the suggestion!

**Comment by dickyjayaumbara** [comment]
wow awesome, Thank you brother!
